---
- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Remove defualt nginx configuration
  file:
    path: "{{item}}"
    state: absent
  notify: restart nginx
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /etc/nginx/conf.d/default
# vim:ft=ansible
